# Generated by Django 2.1 on 2018-08-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0001_basic_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='social_contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackendApp.SocialContacts'),
        ),
    ]
